CREATE TABLE IF NOT EXISTS instituicoes (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug               VARCHAR(60) NOT NULL UNIQUE,
  nome               VARCHAR(120) NOT NULL,
  nome_admin         VARCHAR(120) NOT NULL,
  nome_sistema       VARCHAR(160) NOT NULL,
  subtitulo_admin    VARCHAR(160) NOT NULL,
  logo_url           VARCHAR(500) NULL,
  cor_primaria_hsl   VARCHAR(40) NOT NULL,
  cor_acento_hsl     VARCHAR(40) NOT NULL,
  cor_header_hsl     VARCHAR(40) NOT NULL,
  cor_nav_hsl        VARCHAR(40) NOT NULL,
  cor_nav_ativa_hsl  VARCHAR(40) NOT NULL,
  ativo              BOOLEAN NOT NULL DEFAULT TRUE,
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO instituicoes
  (slug, nome, nome_admin, nome_sistema, subtitulo_admin, cor_primaria_hsl, cor_acento_hsl, cor_header_hsl, cor_nav_hsl, cor_nav_ativa_hsl)
VALUES
  ('cimol', 'CIMOL', 'CIMOL Admin', 'Sistema de Gestão Escolar', 'Painel Administrativo', '228 65% 48%', '45 100% 51%', '228 62% 32%', '228 62% 42%', '228 50% 52%')
ON CONFLICT (slug) DO NOTHING;

CREATE TABLE IF NOT EXISTS alunos (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instituicao_id INTEGER NOT NULL,
  nome        VARCHAR(120) NOT NULL,
  ano         VARCHAR(20)  NOT NULL,
  turma       VARCHAR(30)  NOT NULL,
  curso       VARCHAR(80)  NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_alunos_lookup
  ON alunos (nome, ano, turma, curso);

CREATE TABLE IF NOT EXISTS reorganizacoes (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aluno_id      INTEGER NOT NULL REFERENCES alunos(id) ON DELETE CASCADE,
  problema      TEXT NOT NULL,
  arquivo_nome  VARCHAR(255) NULL,
  arquivo_dados BYTEA NULL,
  data          DATE NOT NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_reorganizacoes_data
  ON reorganizacoes (data, id);

CREATE INDEX IF NOT EXISTS idx_reorganizacoes_aluno
  ON reorganizacoes (aluno_id);

CREATE TABLE IF NOT EXISTS reorganizacao_salas_relacionadas (
  reorganizacao_id INTEGER NOT NULL REFERENCES reorganizacoes(id) ON DELETE CASCADE,
  sala             VARCHAR(50) NOT NULL,
  PRIMARY KEY (reorganizacao_id, sala)
);

CREATE TABLE IF NOT EXISTS usuarios (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instituicao_id INTEGER NOT NULL,
  nome        VARCHAR(120) NOT NULL,
  usuario     VARCHAR(80) NOT NULL,
  senha_hash  VARCHAR(128) NOT NULL,
  senha_salt  VARCHAR(64) NOT NULL,
  papel       VARCHAR(10) NOT NULL CHECK (papel IN ('ADMIN', 'CPD')),
  gerencia_instituicoes BOOLEAN NOT NULL DEFAULT FALSE,
  ativo       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_usuarios_instituicao_usuario UNIQUE (instituicao_id, usuario)
);

CREATE TABLE IF NOT EXISTS sessoes (
  token_hash  CHAR(64) PRIMARY KEY,
  usuario_id  INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  expires_at  TIMESTAMP NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sessoes_usuario
  ON sessoes (usuario_id);

CREATE INDEX IF NOT EXISTS idx_sessoes_expiracao
  ON sessoes (expires_at);

CREATE TABLE IF NOT EXISTS blocos (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instituicao_id INTEGER NOT NULL,
  nome        VARCHAR(120) NOT NULL,
  descricao   TEXT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_blocos_instituicao_nome UNIQUE (instituicao_id, nome)
);

CREATE TABLE IF NOT EXISTS salas (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instituicao_id         INTEGER NOT NULL,
  bloco_id              INTEGER NOT NULL REFERENCES blocos(id) ON DELETE RESTRICT,
  nome                  VARCHAR(120) NOT NULL,
  andar                 VARCHAR(40) NOT NULL,
  capacidade            INTEGER NULL CHECK (capacidade IS NULL OR capacidade >= 0),
  tipo                  VARCHAR(80) NOT NULL,
  status                VARCHAR(20) NOT NULL DEFAULT 'ATIVA' CHECK (status IN ('ATIVA', 'INATIVA', 'MANUTENCAO')),
  acessivel             BOOLEAN NOT NULL DEFAULT FALSE,
  possui_computadores   BOOLEAN NOT NULL DEFAULT FALSE,
  possui_data_show      BOOLEAN NOT NULL DEFAULT FALSE,
  possui_internet       BOOLEAN NOT NULL DEFAULT FALSE,
  possui_ar_condicionado BOOLEAN NOT NULL DEFAULT FALSE,
  observacoes           TEXT NULL,
  created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_salas_instituicao_bloco_nome UNIQUE (instituicao_id, bloco_id, nome)
);

CREATE INDEX IF NOT EXISTS idx_salas_recursos
  ON salas (possui_computadores, possui_data_show, possui_internet, possui_ar_condicionado);

CREATE INDEX IF NOT EXISTS idx_salas_capacidade
  ON salas (capacidade);

CREATE INDEX IF NOT EXISTS idx_salas_bloco_andar_nome
  ON salas (bloco_id, andar, nome);

CREATE INDEX IF NOT EXISTS idx_salas_tipo
  ON salas (tipo);

CREATE TABLE IF NOT EXISTS softwares (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instituicao_id INTEGER NOT NULL,
  nome        VARCHAR(120) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_softwares_instituicao_nome UNIQUE (instituicao_id, nome)
);

CREATE TABLE IF NOT EXISTS sala_softwares (
  sala_id      INTEGER NOT NULL REFERENCES salas(id) ON DELETE CASCADE,
  software_id  INTEGER NOT NULL REFERENCES softwares(id) ON DELETE CASCADE,
  PRIMARY KEY (sala_id, software_id)
);

CREATE INDEX IF NOT EXISTS idx_sala_softwares_software
  ON sala_softwares (software_id);

CREATE TABLE IF NOT EXISTS eventos (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instituicao_id INTEGER NOT NULL,
  titulo       VARCHAR(140) NOT NULL,
  descricao    TEXT NULL,
  data_evento  DATE NOT NULL,
  hora_evento  TIME NULL,
  local        VARCHAR(140) NULL,
  imagem_url   VARCHAR(500) NULL,
  ativo        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_eventos_publicos
  ON eventos (ativo, data_evento, id);

CREATE TABLE IF NOT EXISTS setores (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instituicao_id        INTEGER NOT NULL,
  nome                 VARCHAR(120) NOT NULL,
  descricao            VARCHAR(255) NOT NULL,
  responsavel          VARCHAR(120) NULL,
  localizacao          VARCHAR(160) NULL,
  contato              VARCHAR(160) NULL,
  horario_atendimento  VARCHAR(160) NULL,
  icone                VARCHAR(40) NOT NULL DEFAULT 'building',
  cor                  VARCHAR(40) NOT NULL DEFAULT 'blue',
  ativo                BOOLEAN NOT NULL DEFAULT TRUE,
  created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_setores_publicos
  ON setores (ativo, nome);

CREATE TABLE IF NOT EXISTS ouvidoria_manifestacoes (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instituicao_id INTEGER NOT NULL,
  nome         VARCHAR(120) NULL,
  perfil       VARCHAR(20) NOT NULL CHECK (perfil IN ('ALUNO', 'DOCENTE', 'RESPONSAVEL', 'COMUNIDADE')),
  categoria    VARCHAR(20) NOT NULL CHECK (categoria IN ('IDEIA', 'MELHORIA', 'PROBLEMA', 'AVISO')),
  setor_id     INTEGER NULL REFERENCES setores(id) ON DELETE SET NULL,
  assunto      VARCHAR(120) NOT NULL,
  mensagem     TEXT NOT NULL,
  status       VARCHAR(20) NOT NULL DEFAULT 'NOVA' CHECK (status IN ('NOVA', 'EM_ANALISE', 'RESOLVIDA', 'ARQUIVADA')),
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ouvidoria_status_data
  ON ouvidoria_manifestacoes (status, created_at);

CREATE INDEX IF NOT EXISTS idx_ouvidoria_categoria
  ON ouvidoria_manifestacoes (categoria, created_at);

CREATE INDEX IF NOT EXISTS idx_ouvidoria_setor
  ON ouvidoria_manifestacoes (setor_id);

CREATE TABLE IF NOT EXISTS importacoes_horarios (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instituicao_id      INTEGER NOT NULL,
  fonte              VARCHAR(10) NOT NULL CHECK (fonte IN ('HTML', 'XML', 'MISTO')),
  titulo             VARCHAR(255) NOT NULL,
  escopo_chave       VARCHAR(255) NOT NULL,
  codigo_escola      VARCHAR(25) NULL,
  codigo_turno       VARCHAR(3) NULL,
  nome_turno         VARCHAR(80) NULL,
  status             VARCHAR(20) NOT NULL DEFAULT 'PENDENTE' CHECK (status IN ('PENDENTE', 'APROVADA', 'REJEITADA')),
  ativa              BOOLEAN NOT NULL DEFAULT FALSE,
  lote_hash          CHAR(64) NOT NULL,
  total_arquivos     INTEGER NOT NULL DEFAULT 0 CHECK (total_arquivos >= 0),
  total_horarios     INTEGER NOT NULL DEFAULT 0 CHECK (total_horarios >= 0),
  total_turmas       INTEGER NOT NULL DEFAULT 0 CHECK (total_turmas >= 0),
  avisos_json        JSONB NULL,
  observacoes_envio  TEXT NULL,
  motivo_rejeicao    TEXT NULL,
  enviado_por        INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  revisado_por       INTEGER NULL REFERENCES usuarios(id) ON DELETE SET NULL,
  revisado_em        TIMESTAMP NULL,
  publicado_em       TIMESTAMP NULL,
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_importacoes_status_data
  ON importacoes_horarios (status, created_at);

CREATE INDEX IF NOT EXISTS idx_importacoes_publicacao
  ON importacoes_horarios (ativa, status, escopo_chave);

CREATE INDEX IF NOT EXISTS idx_importacoes_hash
  ON importacoes_horarios (lote_hash);

CREATE INDEX IF NOT EXISTS idx_importacoes_enviado_por
  ON importacoes_horarios (enviado_por);

CREATE INDEX IF NOT EXISTS idx_importacoes_revisado_por
  ON importacoes_horarios (revisado_por);

CREATE TABLE IF NOT EXISTS importacao_arquivos (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  importacao_id  INTEGER NOT NULL REFERENCES importacoes_horarios(id) ON DELETE CASCADE,
  nome           VARCHAR(255) NOT NULL,
  mime_type      VARCHAR(120) NOT NULL,
  tamanho        INTEGER NOT NULL CHECK (tamanho >= 0),
  sha256         CHAR(64) NOT NULL,
  conteudo       BYTEA NOT NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_importacao_arquivos_importacao
  ON importacao_arquivos (importacao_id);

CREATE TABLE IF NOT EXISTS horarios_importados (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  importacao_id   INTEGER NOT NULL REFERENCES importacoes_horarios(id) ON DELETE CASCADE,
  categoria       VARCHAR(20) NOT NULL DEFAULT 'TURMA' CHECK (categoria IN ('TURMA', 'COORDENACAO', 'REUNIAO', 'OUTRO')),
  turma           VARCHAR(120) NOT NULL,
  curso           VARCHAR(120) NULL,
  ano             VARCHAR(20) NULL,
  dia             VARCHAR(3) NOT NULL,
  periodo         SMALLINT NOT NULL CHECK (periodo >= 0),
  hora_inicio     TIME NULL,
  disciplina      VARCHAR(255) NOT NULL,
  professor       VARCHAR(255) NULL,
  ambiente        VARCHAR(120) NULL,
  sala_id         INTEGER NULL REFERENCES salas(id) ON DELETE SET NULL,
  tipo_turma      VARCHAR(20) NULL,
  tipo_disciplina VARCHAR(30) NULL,
  valor_original  TEXT NULL,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_horarios_importacao
  ON horarios_importados (importacao_id);

CREATE INDEX IF NOT EXISTS idx_horarios_publicos
  ON horarios_importados (categoria, turma, dia, periodo);

CREATE INDEX IF NOT EXISTS idx_horarios_publicos_importacao
  ON horarios_importados (importacao_id, categoria, turma, dia, periodo);

CREATE INDEX IF NOT EXISTS idx_horarios_sala
  ON horarios_importados (sala_id);

CREATE TABLE IF NOT EXISTS sala_alteracoes (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  horario_id          BIGINT NOT NULL REFERENCES horarios_importados(id) ON DELETE CASCADE,
  usuario_id          INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
  turma               VARCHAR(120) NOT NULL,
  dia                 VARCHAR(3) NOT NULL,
  periodo             SMALLINT NOT NULL CHECK (periodo >= 0),
  sala_anterior_id    INTEGER NULL REFERENCES salas(id) ON DELETE SET NULL,
  sala_nova_id        INTEGER NULL REFERENCES salas(id) ON DELETE SET NULL,
  quantidade_alunos   INTEGER NULL CHECK (quantidade_alunos IS NULL OR quantidade_alunos >= 0),
  motivo              VARCHAR(255) NULL,
  created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sala_alteracoes_data
  ON sala_alteracoes (created_at, id);

CREATE INDEX IF NOT EXISTS idx_sala_alteracoes_horario
  ON sala_alteracoes (horario_id);

CREATE INDEX IF NOT EXISTS idx_sala_alteracoes_usuario
  ON sala_alteracoes (usuario_id);

CREATE INDEX IF NOT EXISTS idx_sala_alteracoes_sala_anterior
  ON sala_alteracoes (sala_anterior_id);

CREATE INDEX IF NOT EXISTS idx_sala_alteracoes_sala_nova
  ON sala_alteracoes (sala_nova_id);

CREATE TABLE IF NOT EXISTS horario_notificacoes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instituicao_id INTEGER NOT NULL,
  email       VARCHAR(255) NOT NULL,
  turma       VARCHAR(120) NOT NULL,
  ativo       BOOLEAN NOT NULL DEFAULT FALSE,
  confirmacao_token_hash CHAR(64) NULL,
  confirmacao_expira_em TIMESTAMP NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_horario_notificacoes_instituicao_email_turma UNIQUE (instituicao_id, email, turma)
);

CREATE INDEX IF NOT EXISTS idx_horario_notificacoes_turma_ativo
  ON horario_notificacoes (turma, ativo);

CREATE INDEX IF NOT EXISTS idx_horario_notificacoes_token
  ON horario_notificacoes (confirmacao_token_hash);

DO $$
DECLARE
  cimol_id integer;
BEGIN
  SELECT id INTO cimol_id FROM instituicoes WHERE slug = 'cimol' LIMIT 1;
  IF cimol_id IS NULL THEN
    RAISE EXCEPTION 'Instituicao padrao cimol nao encontrada.';
  END IF;

  ALTER TABLE alunos ADD COLUMN IF NOT EXISTS instituicao_id INTEGER;
  ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS instituicao_id INTEGER;
  ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS gerencia_instituicoes BOOLEAN NOT NULL DEFAULT FALSE;
  ALTER TABLE blocos ADD COLUMN IF NOT EXISTS instituicao_id INTEGER;
  ALTER TABLE salas ADD COLUMN IF NOT EXISTS instituicao_id INTEGER;
  ALTER TABLE softwares ADD COLUMN IF NOT EXISTS instituicao_id INTEGER;
  ALTER TABLE eventos ADD COLUMN IF NOT EXISTS instituicao_id INTEGER;
  ALTER TABLE setores ADD COLUMN IF NOT EXISTS instituicao_id INTEGER;
  ALTER TABLE ouvidoria_manifestacoes ADD COLUMN IF NOT EXISTS instituicao_id INTEGER;
  ALTER TABLE importacoes_horarios ADD COLUMN IF NOT EXISTS instituicao_id INTEGER;
  ALTER TABLE horario_notificacoes ADD COLUMN IF NOT EXISTS instituicao_id INTEGER;

  UPDATE alunos SET instituicao_id = cimol_id WHERE instituicao_id IS NULL;
  UPDATE usuarios SET instituicao_id = cimol_id WHERE instituicao_id IS NULL;
  UPDATE usuarios SET gerencia_instituicoes = TRUE WHERE instituicao_id = cimol_id AND papel = 'CPD';
  UPDATE blocos SET instituicao_id = cimol_id WHERE instituicao_id IS NULL;
  UPDATE salas SET instituicao_id = cimol_id WHERE instituicao_id IS NULL;
  UPDATE softwares SET instituicao_id = cimol_id WHERE instituicao_id IS NULL;
  UPDATE eventos SET instituicao_id = cimol_id WHERE instituicao_id IS NULL;
  UPDATE setores SET instituicao_id = cimol_id WHERE instituicao_id IS NULL;
  UPDATE ouvidoria_manifestacoes SET instituicao_id = cimol_id WHERE instituicao_id IS NULL;
  UPDATE importacoes_horarios SET instituicao_id = cimol_id WHERE instituicao_id IS NULL;
  UPDATE horario_notificacoes SET instituicao_id = cimol_id WHERE instituicao_id IS NULL;

  ALTER TABLE alunos ALTER COLUMN instituicao_id SET NOT NULL;
  ALTER TABLE usuarios ALTER COLUMN instituicao_id SET NOT NULL;
  ALTER TABLE blocos ALTER COLUMN instituicao_id SET NOT NULL;
  ALTER TABLE salas ALTER COLUMN instituicao_id SET NOT NULL;
  ALTER TABLE softwares ALTER COLUMN instituicao_id SET NOT NULL;
  ALTER TABLE eventos ALTER COLUMN instituicao_id SET NOT NULL;
  ALTER TABLE setores ALTER COLUMN instituicao_id SET NOT NULL;
  ALTER TABLE ouvidoria_manifestacoes ALTER COLUMN instituicao_id SET NOT NULL;
  ALTER TABLE importacoes_horarios ALTER COLUMN instituicao_id SET NOT NULL;
  ALTER TABLE horario_notificacoes ALTER COLUMN instituicao_id SET NOT NULL;

  ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_usuario_key;
  ALTER TABLE blocos DROP CONSTRAINT IF EXISTS blocos_nome_key;
  ALTER TABLE salas DROP CONSTRAINT IF EXISTS uq_salas_bloco_nome;
  ALTER TABLE softwares DROP CONSTRAINT IF EXISTS softwares_nome_key;
  ALTER TABLE horario_notificacoes DROP CONSTRAINT IF EXISTS uq_horario_notificacoes_email_turma;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_alunos_instituicao') THEN
    ALTER TABLE alunos ADD CONSTRAINT fk_alunos_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_usuarios_instituicao') THEN
    ALTER TABLE usuarios ADD CONSTRAINT fk_usuarios_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_blocos_instituicao') THEN
    ALTER TABLE blocos ADD CONSTRAINT fk_blocos_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_salas_instituicao') THEN
    ALTER TABLE salas ADD CONSTRAINT fk_salas_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_softwares_instituicao') THEN
    ALTER TABLE softwares ADD CONSTRAINT fk_softwares_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_eventos_instituicao') THEN
    ALTER TABLE eventos ADD CONSTRAINT fk_eventos_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_setores_instituicao') THEN
    ALTER TABLE setores ADD CONSTRAINT fk_setores_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ouvidoria_instituicao') THEN
    ALTER TABLE ouvidoria_manifestacoes ADD CONSTRAINT fk_ouvidoria_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_importacoes_instituicao') THEN
    ALTER TABLE importacoes_horarios ADD CONSTRAINT fk_importacoes_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_horario_notificacoes_instituicao') THEN
    ALTER TABLE horario_notificacoes ADD CONSTRAINT fk_horario_notificacoes_instituicao FOREIGN KEY (instituicao_id) REFERENCES instituicoes(id) ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_usuarios_instituicao_usuario') THEN
    ALTER TABLE usuarios ADD CONSTRAINT uq_usuarios_instituicao_usuario UNIQUE (instituicao_id, usuario);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_blocos_instituicao_nome') THEN
    ALTER TABLE blocos ADD CONSTRAINT uq_blocos_instituicao_nome UNIQUE (instituicao_id, nome);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_salas_instituicao_bloco_nome') THEN
    ALTER TABLE salas ADD CONSTRAINT uq_salas_instituicao_bloco_nome UNIQUE (instituicao_id, bloco_id, nome);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_softwares_instituicao_nome') THEN
    ALTER TABLE softwares ADD CONSTRAINT uq_softwares_instituicao_nome UNIQUE (instituicao_id, nome);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_horario_notificacoes_instituicao_email_turma') THEN
    ALTER TABLE horario_notificacoes ADD CONSTRAINT uq_horario_notificacoes_instituicao_email_turma UNIQUE (instituicao_id, email, turma);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_alunos_instituicao_lookup
  ON alunos (instituicao_id, nome, ano, turma, curso);

CREATE INDEX IF NOT EXISTS idx_eventos_instituicao_publicos
  ON eventos (instituicao_id, ativo, data_evento, id);

CREATE INDEX IF NOT EXISTS idx_setores_instituicao_publicos
  ON setores (instituicao_id, ativo, nome);

CREATE INDEX IF NOT EXISTS idx_ouvidoria_instituicao_status_data
  ON ouvidoria_manifestacoes (instituicao_id, status, created_at);

CREATE INDEX IF NOT EXISTS idx_importacoes_instituicao_publicacao
  ON importacoes_horarios (instituicao_id, ativa, status, escopo_chave);

CREATE INDEX IF NOT EXISTS idx_horario_notificacoes_instituicao_turma_ativo
  ON horario_notificacoes (instituicao_id, turma, ativo);

DO $$
DECLARE
  target_table text;
BEGIN
  FOREACH target_table IN ARRAY ARRAY[
    'alunos',
    'instituicoes',
    'reorganizacoes',
    'reorganizacao_salas_relacionadas',
    'usuarios',
    'sessoes',
    'blocos',
    'salas',
    'softwares',
    'sala_softwares',
    'eventos',
    'setores',
    'ouvidoria_manifestacoes',
    'importacoes_horarios',
    'importacao_arquivos',
    'horarios_importados',
    'sala_alteracoes',
    'horario_notificacoes'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', target_table);
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS usuarios_set_updated_at ON usuarios;
CREATE TRIGGER usuarios_set_updated_at
  BEFORE UPDATE ON usuarios
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS instituicoes_set_updated_at ON instituicoes;
CREATE TRIGGER instituicoes_set_updated_at
  BEFORE UPDATE ON instituicoes
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS blocos_set_updated_at ON blocos;
CREATE TRIGGER blocos_set_updated_at
  BEFORE UPDATE ON blocos
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS salas_set_updated_at ON salas;
CREATE TRIGGER salas_set_updated_at
  BEFORE UPDATE ON salas
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS eventos_set_updated_at ON eventos;
CREATE TRIGGER eventos_set_updated_at
  BEFORE UPDATE ON eventos
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS setores_set_updated_at ON setores;
CREATE TRIGGER setores_set_updated_at
  BEFORE UPDATE ON setores
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS ouvidoria_set_updated_at ON ouvidoria_manifestacoes;
CREATE TRIGGER ouvidoria_set_updated_at
  BEFORE UPDATE ON ouvidoria_manifestacoes
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS importacoes_set_updated_at ON importacoes_horarios;
CREATE TRIGGER importacoes_set_updated_at
  BEFORE UPDATE ON importacoes_horarios
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS horario_notificacoes_set_updated_at ON horario_notificacoes;
CREATE TRIGGER horario_notificacoes_set_updated_at
  BEFORE UPDATE ON horario_notificacoes
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
