CREATE DATABASE IF NOT EXISTS cimol
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE cimol;

CREATE TABLE IF NOT EXISTS reorganizacao_salas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  aluno VARCHAR(120) NOT NULL,
  ano VARCHAR(20) NOT NULL,
  turma VARCHAR(30) NOT NULL,
  curso VARCHAR(80) NOT NULL,
  problema TEXT NOT NULL,
  salas VARCHAR(255) NOT NULL,
  data DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
